### PR TITLE
extra functions to get external data

### PR DESCRIPTION
**Pull request by hansvancalster**
@florisvdh a suggestion to have some functions to retrieve data from zenodo and network stations. This is not working yet (except for one function that writes the data folders), but can be worked on  further if you think it is useful.

### CODE REVIEW

**Comment by florisvdh** [comment]
This would be an interesting feature indeed. Thank you for starting this! As this was only an optional feature, I earlier omitted that from [intended](https://docs.google.com/spreadsheets/d/18U4AmiMnnApbgQTnfWbeZ3dAH3_4ISxUob_SX-maKV8/edit#gid=0) behaviour. Anyhow, the retrieval of data should be consistent with the needed versions for an analysis workflow.

Central to the current setup (cf. cell b75 [here](https://docs.google.com/spreadsheets/d/18U4AmiMnnApbgQTnfWbeZ3dAH3_4ISxUob_SX-maKV8/edit#gid=0&range=B75)) is that for a _n2khab_ analysis workflow:

- a table is to be made (current working name: `datalist_chosen`), specific to the workflow, that defines the versions of the data sources to be used (raw, processed) and required to be present. The IDs of data sources and their versions, and the associated file hashes are defined [here](https://docs.google.com/spreadsheets/d/1E8ERlfYwP3OjluL8d7_4rR1W34ka4LRCE35JTxf3WMI). Format still to be worked out, you're free to pick this up!
Something of the form:

  | datasource_id_needed  | version_id_needed |
  | ------------- | ------------- |
  | habitatmap  | habitatmap_2018  |
  | soilmap  | soilmap_2017-06-20  |
  | types  | tagXXX  |

  How we will define certain versions of the (textual) `reference lists` from `n2khabutils`, is still to be decided, e.g. with git tags (you may want to stay with a specific version for stability, or just to be able to reproduce a historical workflow). And these can then also be defined in the googlesheet as data versions. Retrieval from the github repo is an obvious solution here.

- textual counterparts of (necessary columns of) the data sources and their versions + files (tabs in the referred googlesheet) should become part of the `n2khabutils` package as well. See intended data sources `datasources` and `dataversions`. _To do._
- a dataversion checking function can then be concipiated, as circumscribed in that cell b75. It verifies if the dataversions are present as defined by the user for a specific workflow in `datalist_chosen`. _To do._ You can find a method for file hash calculation (currently implemented for the enlisted files in the gsheet) in `src/compute_sha256.R`.

All of this has to do with data reproducibility.

If you want to implement data retrieving functions, I suggest that you make it take into account the user's specifications of `datalist_chosen`. Perhaps one overarching function, calling the zenodo-function, the github-function, the amazon-function, ... would be perfect. Further, it could at once call the data checking function, to make sure the downloaded data are not corrupted (or even, the online source).

You are very welcome to take up the above.

**Comment by florisvdh** [comment]
At this point, I think your idea of a function to automatically create empty 'data' folders is great. Will test it!

**Comment by florisvdh** [comment]
Still regarding the data retrieval option, you can also have a look at [this](https://github.com/inbo/n2khab-inputs/issues/2#issuecomment-470158563) comment, where Stijn referred to another repo with examples.

**Comment by hansvancalster** [comment]
I read a bit about getting data from zenodo. I think a combination of the Python function [zenodo_get](https://gitlab.com/dvolgyes/zenodo_get) and the [reticulate package](https://rstudio.github.io/reticulate/articles/package.html) should make it possible. 

Do you have an example of an INBO zenodo doi?

**Comment by florisvdh** [comment]
Sounds highly interesting. Here you go for _the_ currently involved Zenodo dataset :-): https://zenodo.org/record/2611234 for both versions (@ToonHub will update the name / metadata of the most recent one: https://zenodo.org/record/2682323 ).

You find these metadata in the datasources googlesheet (referred from my first comment, cf. datamanagement.md and the package vignette)

Perhaps the [oai](https://github.com/ropensci/oai) R package may be of help as well. Perhaps @stijnvanhoey and @peterdesmet have suggestions too.

For preceeding discussions that led to current data management choices, see [this](https://docs.google.com/document/d/1ttUI4ZERKX4Y0p6w17JjQ_KGgKFSkEwcXSKLxwm1Xyk) gdoc (minutes of a meeting in January).

**Comment by florisvdh** [comment]
See https://www.r-bloggers.com/querying-zenodo-org-repository-with-r/

**Comment by hansvancalster** [comment]
I looked at both options, but neither are suitable. The Python route is overkill (need to install 0.5 GB of software to make it work...). The oai package and [https://zenodo.org/oai2d](https://zenodo.org/oai2d) seem only to allow gathering metadata. 

@ThierryO suggested a simpler approach: only put the url/doi in the script and manually download the data. 

I suggest closing the PR? Unless someone else has good ideas.

**Comment by florisvdh** [comment]
@hansvancalster Regarding your last comment, I would not let fall the data-creation-function, see my review. Plus you can also broaden the scope to filemanagement in general (rename `get_external_data.R` into `filemanagement.R`) and proceed.

**Comment by hansvancalster** [comment]
OK, thanks for the review! I take it further up next week.

**Comment by florisvdh** [comment]
The `filemanag_folders()` function works fluently, thanks so much! (tested the three distinguished cases)

I'll propose a few extra suggestions as a separate PR: some cosmetic, some to make `R CMD check` succeed & not complaining, some to prevent the two dummy functions to currently appear in the documentation. After handling that PR, I suggest you merge your own PR (this one) - you can still work further in your branch after merging.

**Comment by hansvancalster** [comment]
@florisvdh you wrote: "you can still work further in your branch after merging". I didn't know this is possible. How does it work?

**Comment by florisvdh** [comment]
@hansvancalster it works the same as before, i.e. as long as you don't delete the remote branch (but I see you restored it. Another way to get around a deleted remote branch is just pushing the branch again in the same way (`git push -u origin <branchname>`) as you did the very first time).

As you have the remote branch available, you can push new commits to it. As the current PR was merged, new commits are not added to this PR but only to the branch itself, just the same as before you started your first PR. Your next PR will only distinguish the commits that were not yet merged into the target branch, and so the story continues.

All in all, it is similar to just starting a new branch and starting the story over. I think you better do that anyway whenever the the branch's name does not longer reflect what is in it. So I would restrict 'keeping the branch and doing more work in it' to cases where you work further on the same subject, after a PR was merged.

**Comment by hansvancalster** [comment]
Thanks for the explanation. That's crystal clear.

**Pull request merged**
