### PR TITLE
Readme update + functionality requirements

### PR DESCRIPTION
**Pull request by florisvdh**
Start with reading the readme; the rest is referred from there.

- [github's rendered README.md](https://github.com/inbo/n2khab-inputs/blob/add_functionality_requirements/README.md)
- [github's rendered functionality.md](https://github.com/inbo/n2khab-inputs/blob/add_functionality_requirements/functionality.md)

### CODE REVIEW

**Comment by florisvdh** [comment]
@hansvancalster thanks for your feedback!

Regarding the subfolders, I am also a bit unsure. I think the overview of the datasources will be cleaner with subfolders as several data sources exist of more than one file (e.g. shapefiles). On the other hand, it is not needed for functioning.

**Comment by florisvdh** [comment]
@hansvancalster Another reflection on the data subfolders (1 subfolder for 1 data source). In functionality to check the data source against the required version (defined in a separate table), a separate (git-ignored) file is foreseen to be written next to each datafile. That file will store output from `file.info()` so that later it can be easily seen whether something might have changed with the file (especially the timestamp), and therefore to decide if a checksum needs to be calculated and checked.

**Comment by hansvancalster** [comment]
That's a good idea and it will probably work best with 1 subfolder for 1 data source.

**Comment by florisvdh** [comment]
@ToonHub @DriesAdriaens I updated the readme/datamanagement/functionality-instructions in this branch, according to earlier discussion and issue #2 on binary data location and the R-package.

You may want to have a quick look at the [recent file changes](https://github.com/inbo/n2khab-inputs/pull/3/files/3fad5da0280a6f750eeddac3e4d5cff447bbb282..ba432e565eb070271de990237b0c5f208e1191b3); however this pull request should be fine for merging.

Next steps from my side are:

- making the data tasks (which are already defined by the [googlesheet](https://docs.google.com/spreadsheets/d/1E8ERlfYwP3OjluL8d7_4rR1W34ka4LRCE35JTxf3WMI) + workflow [scheme](https://drive.google.com/open?id=1xZz9f9n8zSUxBJvW6WEFLyDK7Ya0u4iN) + issue #1) explicit within this repo (for better overview and follow-up)
- initializing the package structure

These should normally not impact readme etc. further.

**Comment by florisvdh** [comment]
@DriesAdriaens I added a simple R script `src/compute_sha256.R` (in this branch, `add_functionality_requirements`) for computing file hashes (SHA256) of all files in a directory (including subdirectories). You can use this to generate the file hashes (saved in csv) and enter these in the googlesheet.

The script will serve a precursor of a hashing function in the package.

**Comment by florisvdh** [comment]
Shall I merge this into master? If no further comments arise, I'll merge ;-)

**Pull request merged**
